name: Greeting from Mona
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: download-and
      run: |
        cd openwrt-18.06
        mv .confg.sf1200 .config
        ./scripts/feeds update -a && ./scripts/feeds install -a
        make download && make V=99
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: 'packages'
        # A file, directory or wildcard pattern that describes what to upload
        path: ./bin/targets/siflower/packages
        
