name: Greeting from Mona
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: set-env
      run: |
        echo -e "Total CPU cores\t: $(nproc)"
        sudo apt update
        sudo apt install build-essential gawk gcc-multilib flex git gettext libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev
    - name: download-and
      run: |
        echo -e "Total CPU cores\t: $(nproc)"
        cd openwrt-18.06
        pwd
        mv .config.sft1200 .config
        rm -rf package/helloworld
        sed -i 's/# CONFIG_ALL .*/CONFIG_ALL=y/' .config
        ./scripts/feeds update -a && ./scripts/feeds install custom
        make download -j$(nproc)
        make tools/install -j$(nproc)
        make toolchain/install -j$(nproc)
    - name: compile-packages
      run: |
        pwd
        cd openwrt-18.06
        make package/compile -i -j$(nproc) V=99
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: 'packages'
        # A file, directory or wildcard pattern that describes what to upload
        path: openwrt-18.06/bin/targets/siflower/packages
        
